_player_turn(xplayer, 1) :- movetimedomain(1).
_player_turn(xplayer, 2) :- movetimedomain(2).
_player_turn(oplayer, 3) :- movetimedomain(3).
_player_turn(oplayer, 4) :- movetimedomain(4).
_player_turn(xplayer, 5) :- movetimedomain(5).
_player_turn(xplayer, 6) :- movetimedomain(6).
_player_turn(oplayer, 7) :- movetimedomain(7).
_player_turn(oplayer, 8) :- movetimedomain(8).
_player_turn(xplayer, 9) :- movetimedomain(9).
_player_turn(xplayer, 10) :- movetimedomain(10).
_player_turn(oplayer, 11) :- movetimedomain(11).
_player_turn(oplayer, 12) :- movetimedomain(12).
_player_turn(xplayer, 13) :- movetimedomain(13).
_player_turn(xplayer, 14) :- movetimedomain(14).
_player_turn(oplayer, 15) :- movetimedomain(15).
_player_turn(oplayer, 16) :- movetimedomain(16).
